# Generated by Django 4.1.7 on 2023-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('debt_sum', models.IntegerField()),
                ('return_date', models.DateField()),
                ('take_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
