# Generated by Django 4.1.7 on 2023-05-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyGiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('take_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('money_giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='debtlist.moneygiver')),
            ],
            options={
                'ordering': ['money_giver'],
            },
        ),
    ]
