# Generated by Django 4.1.7 on 2023-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
