# Generated by Django 4.1.7 on 2023-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0009_remove_debt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneygiver',
            old_name='name',
            new_name='name1',
        ),
    ]
