# Generated by Django 4.1.7 on 2023-05-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0010_rename_name_moneygiver_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneygiver',
            name='id',
        ),
        migrations.AddField(
            model_name='debt',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='debtlist.moneygiver'),
        ),
        migrations.AlterField(
            model_name='moneygiver',
            name='name1',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
