# Generated by Django 4.1.7 on 2023-03-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='debt',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='take_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
