# Generated by Django 4.1.7 on 2023-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0002_alter_debt_debt_sum_alter_debt_return_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['id']},
        ),
    ]
