# Generated by Django 4.1.7 on 2023-04-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0004_debt_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='cat',
        ),
        migrations.AlterField(
            model_name='debt',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='debtlist.moneygiver'),
        ),
    ]
