# Generated by Django 4.1.7 on 2023-05-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0005_remove_debt_cat_alter_debt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='name',
            new_name='debt',
        ),
    ]
