# Generated by Django 4.1.7 on 2023-05-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0006_rename_name_debt_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='debt',
            new_name='name',
        ),
    ]
