# Generated by Django 4.1.7 on 2023-05-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0007_rename_debt_debt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneygiver',
            name='phone_number',
        ),
    ]
