# Generated by Django 4.1.7 on 2023-05-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0008_remove_moneygiver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='name',
        ),
    ]
