# Generated by Django 4.1.7 on 2023-05-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtlist', '0012_alter_debt_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='moneygiver',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='moneygiver',
            name='name1',
        ),
        migrations.AddField(
            model_name='moneygiver',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneygiver',
            name='name',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='debtlist.debt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
